
import { addDays, format, startOfToday } from 'date-fns';
import type { Event } from './types';

const eventsData: Event[] = [
  {
    id: '1',
    title: 'Indie-Nacht in der Palette',
    description:
      "Erlebe das Beste von lokalen und internationalen Indie-Bands in der legendären Palette. Eine Nacht mit großartiger Musik, günstigen Getränken und guter Stimmung erwartet dich. Verpasse nicht das nächste große Ding!",
    date: "2026-02-07",
    category: "Musik",
    location: "Palette, Große Ulrichstraße 51, 06108 Halle (Saale)",
    latitude: 51.4833,
    longitude: 11.9667,
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageHint: "konzert musik",
    ticketUrl: "#",
    categories: ["Musik", "Konzert"],
    time: {
      start: "2026-02-07T20:00:00Z",
      end: "2026-02-08T00:00:00Z",
    },
    district: "Giebichenstein",
    venue: "Palette",
    price: 5,
    isFree: false,
    targetGroups: ["Studierende", "Erwachsene"],
    accessibility: [],
    extras: ["Online-Tickets", "Abendkasse"],
    soldOut: false,
    duration: 4,
    priority: 'Top-Event',
  },
  {
    id: '2',
    title: "Moderne Kunst Vernissage: 'Dimensionen'",
    description:
      "Besuche die Eröffnung von 'Dimensionen', einer neuen Ausstellung der aufstrebenden Künstlerin Klara Weiss. Entdecke abstrakte Formen und lebendige Farben, die die Wahrnehmung herausfordern. Freier Eintritt & kostenloser Sekt.",
    date: "2026-02-10",
    category: "Kunst",
    location: "Kunstmuseum Moritzburg, Friedemann-Bach-Platz 5, 06108 Halle (Saale)",
    latitude: 51.4856,
    longitude: 11.9669,
    imageUrl: "https://images.unsplash.com/photo-1543439613-796955720b73?q=80&w=2838&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageHint: "kunstgalerie",
    ticketUrl: "#",
    categories: ["Kunst", "Ausstellung"],
    time: {
      start: "2026-02-10T19:00:00Z",
      end: "2026-02-10T22:00:00Z",
    },
    district: "Innenstadt",
    venue: "Kunstmuseum Moritzburg",
    price: 0,
    isFree: true,
    targetGroups: ["Erwachsene", "Senioren", "Studierende"],
    accessibility: ["Rollstuhlgerecht", "Barrierefreie Toilette"],
    extras: [],
    soldOut: false,
    duration: 3,
    priority: 'Empfohlen',
  },
  {
    id: '3',
    title: 'Studenten-Techno-Rave',
    description:
      "Entfessle deine Energie bei unserem riesigen Studenten-Techno-Rave. Top lokale DJs legen die ganze Nacht harte Tracks auf. Besondere Studentenrabatte an der Bar.",
    date: "2026-02-12",
    category: "Party",
    location: "Station Endlos, Willy-Brandt-Straße 78, 06110 Halle (Saale)",
    latitude: 51.4701,
    longitude: 11.9852,
    imageUrl: "https://images.unsplash.com/photo-1588117305388-c261e2a87a2d?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageHint: "dj party",
    ticketUrl: "#",
    categories: ["Party", "Musik"],
    time: {
      start: "2026-02-12T23:00:00Z",
      end: "2026-02-13T05:00:00Z",
    },
    district: "Innenstadt",
    venue: "Station Endlos",
    price: 10,
    isFree: false,
    targetGroups: ["Studierende"],
    accessibility: [],
    extras: ["Online-Tickets", "Abendkasse"],
    soldOut: false,
    duration: 6,
    priority: 'Top-Event',
  },
  {
    id: '4',
    title: 'Hallesches Streetball-Turnier',
    description:
      "Hast du das Zeug dazu? Bilde ein Team und tritt beim jährlichen Halleschen Streetball-Turnier an. Preise, Musik und ein Food-Truck-Festival machen dies zu einem Muss für alle Basketball-Liebhaber.",
    date: "2026-02-14",
    category: "Sport",
    location: "Peißnitzinsel, 06108 Halle",
    latitude: 51.487,
    longitude: 11.956,
    imageUrl: "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageHint: "bälle sport",
    ticketUrl: "#",
    categories: ["Sport"],
    time: {
      start: "2026-02-14T12:00:00Z",
      end: "2026-02-14T20:00:00Z",
    },
    district: "Peißnitz",
    venue: "Peißnitzinsel",
    price: 5,
    isFree: false,
    targetGroups: ["Familien", "Kinder", "Studierende", "Erwachsene"],
    accessibility: [],
    extras: ["Outdoor", "Online-Tickets", "Abendkasse"],
    soldOut: false,
    duration: 8,
    priority: 'Top-Event',
  },
  {
    id: '5',
    title: 'Einführung in React: Programmier-Workshop',
    description:
      "Lerne die Grundlagen von React.js in diesem praxisnahen Workshop für Anfänger. Perfekt für Studierende, die moderne Webanwendungen erstellen möchten. Bitte eigenen Laptop mitbringen.",
    date: "2026-02-18",
    category: "Workshop",
    location: "MLU Weinberg Campus, Von-Danckelmann-Platz 1, 06120 Halle",
    latitude: 51.491,
    longitude: 11.934,
    imageUrl: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageHint: "programmier workshop",
    ticketUrl: "#",
    categories: ["Workshop", "Bildung", "Veranstaltungen der MLU"],
    time: {
      start: "2026-02-18T17:00:00Z",
      end: "2026-02-18T20:00:00Z",
    },
    district: "Weinberg Campus",
    venue: "MLU Weinberg Campus",
    price: 0,
    isFree: true,
    targetGroups: ["Studierende"],
    accessibility: ["Rollstuhlgerecht"],
    extras: ["Anmeldung erforderlich"],
    soldOut: false,
    duration: 3,
    priority: 'Empfohlen',
  },
  {
    id: '6',
    title: 'Akustik Open-Air am Turm',
    description:
      "Teile dein Talent oder entdecke neue Künstler bei unserer gemütlichen Akustik Open-Mic-Nacht. Sänger, Dichter und Geschichtenerzähler sind alle willkommen. Die Anmeldung beginnt um 19:30 Uhr.",
    date: "2026-02-21",
    category: "Musik",
    location: "Turm, Friedemann-Bach-Platz 5, 06108 Halle (Saale)",
    latitude: 51.4856,
    longitude: 11.9669,
    imageUrl: "https://images.unsplash.com/photo-1499415479124-73d324915622?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    imageHint: "mikrofon und note",
    ticketUrl: "#",
    price: 5,
    duration: 3,
    extras: ["Abendkasse"],
    isFree: false,
    soldOut: false,
    time: {
        start: "2026-02-21T20:00:00Z",
        end: "2026-02-21T23:00:00Z",
    },
    district: "Innenstadt",
    venue: "Turm",
    targetGroups: ["Alle"],
    accessibility: [],
    categories: ["Musik", "Open-Mic"],
    priority: 'Empfohlen',
  },
  {
    id: '7',
    title: 'Jazzabend im Objekt 5',
    description: 'Genieße einen entspannten Abend mit Live-Jazzmusik in der einzigartigen Atmosphäre des Objekt 5. Erlebe talentierte lokale Musiker und genieße dazu kühle Getränke.',
    date: '2026-02-25',
    category: 'Musik',
    location: 'Objekt 5, Seebener Straße 5, 06114 Halle (Saale)',
    imageUrl: '/images/jazz-abend.jpg',
    imageHint: 'Jazz-Club-Atmosphäre mit Saxophon',
    ticketUrl: '#',
    price: 12,
    duration: 3,
    latitude: 51.499,
    longitude: 11.963,
    isFree: false,
    soldOut: false,
    categories: ["Musik", "Jazz"],
    time: {
        start: "2026-02-25T20:00:00Z",
        end: "2026-02-25T23:00:00Z",
    },
    district: "Giebichenstein",
    venue: "Objekt 5",
    targetGroups: ["Erwachsene", "Senioren"],
    accessibility: ["Begrenzt rollstuhlgerecht"],
    extras: ["Bar", "Abendkasse"],
    priority: 'Empfohlen',
  }
];

export function getEvents(): Event[] {
  return eventsData;
}

export function getEventById(id: string): Event | undefined {
  return eventsData.find((event) => event.id === id);
}
