
import { addDays, format, startOfToday } from 'date-fns';
import type { Event } from './types';

const eventsData: Event[] = [
  {
    id: '1',
    title: 'Indie-Nacht in der Palette',
    description:
      "Erlebe das Beste von lokalen und internationalen Indie-Bands in der legendären Palette. Eine Nacht mit großartiger Musik, günstigen Getränken und guter Stimmung erwartet dich. Verpasse nicht das nächste große Ding!",
    date: "2026-02-07",
    category: "Musik",
    location: "Palette, Große Ulrichstraße 51, 06108 Halle (Saale)",
    latitude: 51.4833,
    longitude: 11.9667,
    imageUrl: "/images/indie-nacht.jpg",
    imageHint: "konzert musik",
    ticketUrl: "#",
    categories: ["Musik", "Konzert"],
    time: {
      start: "2026-02-07T20:00:00Z",
      end: "2026-02-08T00:00:00Z",
    },
    district: "Giebichenstein",
    venue: "Palette",
    price: 5,
    isFree: false,
    studentDiscount: true, // Rabatt aktiviert
    studentPrice: 0, // Kostenlos für Studierende
    targetGroups: ["Studierende", "Erwachsene"],
    accessibility: [],
    extras: ["Online-Tickets", "Abendkasse"],
    soldOut: false,
    duration: 4,
    priority: 'Top-Event',
    attendees: [],
    boxOffice: true,
  },
  {
    id: '2',
    title: "Moderne Kunst Vernissage: 'Dimensionen'",
    description:
      "Besuche die Eröffnung von 'Dimensionen', einer neuen Ausstellung der aufstrebenden Künstlerin Klara Weiss. Entdecke abstrakte Formen und lebendige Farben, die die Wahrnehmung herausfordern. Freier Eintritt & kostenloser Sekt.",
    date: "2026-02-10",
    category: "Kunst",
    location: "Kunstmuseum Moritzburg, Friedemann-Bach-Platz 5, 06108 Halle (Saale)",
    latitude: 51.4856,
    longitude: 11.9669,
    imageUrl: "/images/moderne-kunst.jpg",
    imageHint: "kunstgalerie",
    ticketUrl: "#",
    categories: ["Kunst", "Ausstellung"],
    time: {
      start: "2026-02-10T19:00:00Z",
      end: "2026-02-10T22:00:00Z",
    },
    district: "Innenstadt",
    venue: "Kunstmuseum Moritzburg",
    price: 0,
    isFree: true,
    studentDiscount: false,
    targetGroups: ["Erwachsene", "Senioren", "Studierende"],
    accessibility: ["Rollstuhlgerecht", "Barrierefreie Toilette"],
    extras: [],
    soldOut: false,
    duration: 3,
    priority: 'Empfohlen',
    attendees: [],
  },
  {
    id: '3',
    title: 'Studenten-Techno-Rave',
    description:
      "Entfessle deine Energie bei unserem riesigen Studenten-Techno-Rave. Top lokale DJs legen die ganze Nacht harte Tracks auf. Besondere Studentenrabatte an der Bar.",
    date: "2026-02-12",
    category: "Party",
    location: "Station Endlos, Willy-Brandt-Straße 78, 06110 Halle (Saale)",
    latitude: 51.4701,
    longitude: 11.9852,
    imageUrl: "/images/techno-rave.jpg",
    imageHint: "dj party",
    ticketUrl: "#",
    categories: ["Party", "Musik"],
    time: {
      start: "2026-02-12T23:00:00Z",
      end: "2026-02-13T05:00:00Z",
    },
    district: "Innenstadt",
    venue: "Station Endlos",
    price: 10,
    isFree: false,
    studentDiscount: true, // Rabatt aktiviert
    studentPrice: 5, // 5€ für Studierende
    targetGroups: ["Studierende"],
    accessibility: [],
    extras: ["Online-Tickets", "Abendkasse"],
    soldOut: false,
    duration: 6,
    priority: 'Top-Event',
    attendees: [],
    boxOffice: true,
  },
  {
    id: '4',
    title: 'Hallesches Streetball-Turnier',
    description:
      "Hast du das Zeug dazu? Bilde ein Team und tritt beim jährlichen Halleschen Streetball-Turnier an. Preise, Musik und ein Food-Truck-Festival machen dies zu einem Muss für alle Basketball-Liebhaber.",
    date: "2026-02-14",
    category: "Sport",
    location: "Peißnitzinsel, 06108 Halle",
    latitude: 51.487,
    longitude: 11.956,
    imageUrl: "/images/streetball-turnier.jpg",
    imageHint: "bälle sport",
    ticketUrl: "#",
    categories: ["Sport"],
    time: {
      start: "2026-02-14T12:00:00Z",
      end: "2026-02-14T20:00:00Z",
    },
    district: "Peißnitz",
    venue: "Peißnitzinsel",
    price: 5,
    isFree: false,
    studentDiscount: false,
    targetGroups: ["Familien", "Kinder", "Studierende", "Erwachsene"],
    accessibility: [],
    extras: ["Outdoor", "Online-Tickets", "Abendkasse"],
    soldOut: false,
    duration: 8,
    priority: 'Top-Event',
    attendees: [],
  },
  {
    id: '5',
    title: 'Einführung in React: Programmier-Workshop',
    description:
      "Lerne die Grundlagen von React.js in diesem praxisnahen Workshop für Anfänger. Perfekt für Studierende, die moderne Webanwendungen erstellen möchten. Bitte eigenen Laptop mitbringen.",
    date: "2026-02-18",
    category: "Workshop",
    location: "MLU Weinberg Campus, Von-Danckelmann-Platz 1, 06120 Halle",
    latitude: 51.491,
    longitude: 11.934,
    imageUrl: "/images/programmier-workshop.jpg",
    imageHint: "programmier workshop",
    ticketUrl: "#",
    categories: ["Workshop", "Bildung", "Veranstaltungen der MLU"],
    time: {
      start: "2026-02-18T17:00:00Z",
      end: "2026-02-18T20:00:00Z",
    },
    district: "Weinberg Campus",
    venue: "MLU Weinberg Campus",
    price: 0,
    isFree: true,
    studentDiscount: false,
    targetGroups: ["Studierende"],
    accessibility: ["Rollstuhlgerecht"],
    extras: ["Anmeldung erforderlich"],
    soldOut: false,
    duration: 3,
    priority: 'Empfohlen',
    attendees: [],
  },
  {
    id: '6',
    title: 'Akustik Open-Air am Turm',
    description:
      "Teile dein Talent oder entdecke neue Künstler bei unserer gemütlichen Akustik Open-Mic-Nacht. Sänger, Dichter und Geschichtenerzähler sind alle willkommen. Die Anmeldung beginnt um 19:30 Uhr.",
    date: "2026-02-21",
    category: "Musik",
    location: "Turm, Friedemann-Bach-Platz 5, 06108 Halle (Saale)",
    latitude: 51.4856,
    longitude: 11.9669,
    imageUrl: "/images/akustik-open-air.jpg",
    imageHint: "mikrofon und note",
    ticketUrl: "#",
    price: 5,
    duration: 3,
    extras: ["Abendkasse"],
    isFree: false,
    soldOut: false,
    studentDiscount: false,
    time: {
        start: "2026-02-21T20:00:00Z",
        end: "2026-02-21T23:00:00Z",
    },
    district: "Innenstadt",
    venue: "Turm",
    targetGroups: ["Alle"],
    accessibility: [],
    categories: ["Musik", "Open-Mic"],
    priority: 'Empfohlen',
    attendees: [],
    boxOffice: true,
  },
  {
    id: '7',
    title: 'Jazzabend im Objekt 5',
    description: 'Genieße einen entspannten Abend mit Live-Jazzmusik in der einzigartigen Atmosphäre des Objekt 5. Erlebe talentierte lokale Musiker und genieße dazu kühle Getränke.',
    date: '2026-02-25',
    category: 'Musik',
    location: 'Objekt 5, Seebener Straße 5, 06114 Halle (Saale)',
    imageUrl: '/images/jazzabend.jpg',
    imageHint: 'Jazz-Club-Atmosphäre mit Saxophon',
    ticketUrl: '#',
    price: 12,
    duration: 3,
    latitude: 51.499,
    longitude: 11.963,
    isFree: false,
    soldOut: false,
    studentDiscount: false,
    categories: ["Musik", "Jazz"],
    time: {
        start: "2026-02-25T20:00:00Z",
        end: "2026-02-25T23:00:00Z",
    },
    district: "Giebichenstein",
    venue: "Objekt 5",
    targetGroups: ["Erwachsene", "Senioren"],
    accessibility: ["Begrenzt rollstuhlgerecht"],
    extras: ["Bar", "Abendkasse"],
    priority: 'Empfohlen',
    attendees: [],
  },
  {
    id: '8',
    title: 'Die große 80er & 90er Party',
    description: 'Tanze zu den besten Hits der 80er und 90er.',
    date: '2026-01-27',
    category: 'Party',
    location: 'Palette, Große Ulrichstraße 51, 06108 Halle (Saale)',
    imageUrl: '/images/techno-rave.jpg',
    imageHint: '80er & 90er Party',
    ticketUrl: '#',
    price: 10,
    duration: 6,
    latitude: 51.4833,
    longitude: 11.9667,
    isFree: false,
    soldOut: false,
    categories: ["Party", "Musik"],
    time: {
        start: "2026-01-27T22:00:00Z",
        end: "2026-01-28T04:00:00Z",
    },
    district: "Giebichenstein",
    venue: "Palette",
    targetGroups: ["Studierende", "Erwachsene"],
    accessibility: [],
    extras: ["Online-Tickets", "Abendkasse"],
    attendees: [],
    boxOffice: true,
  },
  {
    id: '9',
    title: 'Poetry Slam',
    description: 'Erlebe die besten Poeten der Region.',
    date: '2026-01-27',
    category: 'Kultur',
    location: 'Puschkinhaus, Kardinal-Albrecht-Straße 6, 06108 Halle (Saale)',
    imageUrl: '/images/akustik-open-air.jpg',
    imageHint: 'Poetry Slam',
    ticketUrl: '#',
    price: 7,
    duration: 2.5,
    latitude: 51.4833,
    longitude: 11.9696,
    isFree: false,
    soldOut: false,
    categories: ["Kultur", "Bühne"],
    time: {
        start: "2026-01-27T20:00:00Z",
        end: "2026-01-27T22:30:00Z",
    },
    district: "Innenstadt",
    venue: "Puschkinhaus",
    targetGroups: ["Alle"],
    accessibility: ["Rollstuhlgerecht"],
    extras: ["Abendkasse"],
    attendees: [],
    boxOffice: true,
  },
  {
    id: '10',
    title: 'Stammtisch: Politik & Pizza',
    description: 'Diskutiere aktuelle politische Themen bei entspannter Atmosphäre und leckerer Pizza.',
    date: '2026-01-27',
    category: 'Community',
    location: 'Pizzeria "Da Franco", Große Steinstraße 72, 06108 Halle (Saale)',
    imageUrl: '/images/pizza.jpg',
    imageHint: 'Pizza',
    ticketUrl: '#',
    price: 0,
    duration: 2,
    latitude: 51.4842,
    longitude: 11.971,
    isFree: true,
    soldOut: false,
    categories: ["Community", "Politik"],
    time: {
        start: "2026-01-27T19:00:00Z",
        end: "2026-01-27T21:00:00Z",
    },
    district: "Innenstadt",
    venue: 'Pizzeria "Da Franco"',
    targetGroups: ["Alle"],
    accessibility: [],
    extras: ["Selbstzahler"],
    attendees: [],
  }
];

export function getEvents(): Event[] {
  return eventsData;
}

export function getEventById(id: string): Event | undefined {
  return eventsData.find((event) => event.id === id);
}
